### PR TITLE
Contact Us UI Implementation

### LINKED ISSUE #33: Contact US UI Implementation
## Description:
- Implement Contact Us UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the Contact Us button on HomePage,this page will open
- Make sure that the UI is fully responsive

## Design:
Contact us and feedback page

### PR DESCRIPTION
**Pull request by Soulpurr**
Just created a new pr 
fixes #33

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello Soulpurr, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by Soulpurr** [comment]
> @shreya024  Just created a new pr
i think conflicts are resolved do verify and acknowledge
 fixes #33

**Comment by Soulpurr** [comment]
@shreya024 verify this

**Comment by shreya024** [comment]
@Soulpurr Attach a ss/video on how it looks now

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Soulpurr Make sure to take a pull as there are changes in the folder structure and change path from app/contactus/page.js to src=>app/contactus/page.js. Also sharee ss/video of the changes u hv made

**Comment by shreya024** [comment]
@Soulpurr Make the requested changes with ss to get your PR merged

**Comment by Soulpurr** [comment]
> @Soulpurr Make the requested changes with ss to get your PR merged

Ok

**Comment by Soulpurr** [comment]
> @Soulpurr Make the requested changes with ss to get your PR merged

@shreya024  i have made changes do verify it.
Capture121212
Capture5424

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
