### PR TITLE
Added Contributing Guidelines

### PR DESCRIPTION
**Pull request by shanvijha30**
@shreya024 I have added the Contributing Guidelines as CONTRIBUTING.md file.
Please review it.

### CODE REVIEW

**Comment by shreya024** [comment]
@shanvijha30 Also add a link to this in the README.md

**Comment by shanvijha30** [comment]
@shreya024 Should I add it in the Setting up project section?

**Comment by shreya024** [comment]
> @shreya024 Should I add it in the Setting up project section?

Sure 👍

**Comment by shanvijha30** [comment]
@shreya024 I think so first you need to merge the Contributing Guidelines only after which I will be able to add the link of this in the README.md file.

**Comment by shreya024** [comment]
> @shreya024 I think so first you need to merge the Contributing Guidelines only after which I will be able to add the link of this in the README.md file.

No no u can give relative path

**Comment by shanvijha30** [comment]
Okay 👍🏻

**Comment by shreya024** [comment]
> Okay 👍🏻

@shanvijha30 Add the relative link in the README so I can merge it

**Comment by shanvijha30** [comment]
@shreya024 I have worked on it and will create a PR today.

**Comment by shreya024** [comment]
> @shreya024 I am working on it and will create a PR by today.

Hey @shanvijha30 no need to create another PR ,just push the changes in this branch and it will automatically reflect in your existing PR

**Comment by shanvijha30** [comment]
@shreya024 I have added the link in the README.md file.
Please review it.

**Pull request merged**
