### PR TITLE
Dark mode button

### PR DESCRIPTION
**Pull request by parasss19**
Closes: #62

## Description of Changes
- Added the dark mode button 
- Made changes in  Navbar.js,  global.css, layout.js 

For example:
- Added a new function to handle toggle the dark mode button
- Use the google icons of sun and moon

## Checklist:

- [ x] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [x ] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello parasss19, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by shreya024** [comment]
> Closes: #62
> 
> ## Description of Changes
> * Added the dark mode button
> * Made changes in  Navbar.js,  global.css, layout.js
> 
> For example:
> 
> * Added a new function to handle toggle the dark mode button
> * Use the google icons of sun and moon
> 
> ## Checklist:
> * [ x] My code adheres to the established style guidelines of this project.
> * [x ] I have conducted a self-review of my code.
> * [ x] I have included comments in areas that may be difficult to understand.
> * [x ] I have made corresponding updates to the project documentation.
> * [x ] My changes have not introduced any new warnings.
> 
> ## Updated
> 
> ### hi @shreya024 I added the dark mode button but the current background color (bg-[#152023]) in layout.js is already dark so dark mode is not looking effective so can you change the current background color

@parasss19 You can change the current background color and give it a lighter shade to make the dark theme effective

**Comment by parasss19** [comment]
> > Closes: #62
> > ## Description of Changes
> > 
> > * Added the dark mode button
> > * Made changes in  Navbar.js,  global.css, layout.js
> > 
> > For example:
> > 
> > * Added a new function to handle toggle the dark mode button
> > * Use the google icons of sun and moon
> > 
> > ## Checklist:
> > 
> > * [ x] My code adheres to the established style guidelines of this project.
> > * [x ] I have conducted a self-review of my code.
> > * [ x] I have included comments in areas that may be difficult to understand.
> > * [x ] I have made corresponding updates to the project documentation.
> > * [x ] My changes have not introduced any new warnings.
> > 
> > ## Updated
> > 
> > ### hi @shreya024 I added the dark mode button but the current background color (bg-[#152023]) in layout.js is already dark so dark mode is not looking effective so can you change the current background color
> 
> @parasss19 You can change the current background color and give it a lighter shade to make the dark theme effective

Hi @shreya024 I changed the bg color to make the dark mode effective and also i made the navbar transparent and it will change the color only on scroll

**Comment by parasss19** [comment]
Hey @shreya024 I resolved all the conflicts and added the dark mode button properly and its responsive too So please review it once 
- Just one thing is left i am not able to add the dark mode inside hamburger icon can you help me in this part

**Comment by parasss19** [comment]
Hey @SrijanShovit I changed the theme according to you please review it once

**Review by SrijanShovit — APPROVED** [review]

**Review by shreya024 — CHANGES_REQUESTED** [review]
@parasss19 Resolve the conflicts and push again

**Pull request closed without merging**
