### PR TITLE
update score when option is changed

### PR DESCRIPTION
**Pull request by Akanksha-202**
## Related Issue

Closes: #177 

## Description of Changes
- Added checkboxes instead of radio buttons, for the user to uncheck an option if req (unchecking it ,will subtract the value added earlier)
- Added a done button at the end for confirmation
- Added Modal in order to beautify the display of the score

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.

Please install the following package for Modal:
```bash
npm install react-modal
```

## Screenshots

Original:
https://github.com/SrijanShovit/carbonops-v2/assets/100708686/778f13ed-567c-48a6-b294-3f2af391c8b3

Updated:
https://github.com/SrijanShovit/carbonops-v2/assets/100708686/a408a7eb-31b8-44b1-9a44-9dce9bc6a6d1

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello Akanksha-202, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by Akanksha-202** [comment]
@shreya024 Please merge if its correct

**Comment by shreya024** [comment]
> @shreya024 Please merge if its correct

Resolve the merge conflicts

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Akanksha-202 Resolve the merge conflicts and I'll merge

**Comment by Akanksha-202** [comment]
@shreya024 resolved!

**Comment by Akanksha-202** [comment]
> @Akanksha-202 Resolve the merge conflicts and I'll merge

@shreya024 can you please review and merge?

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
