### PR TITLE
feat: Created carbon footprint calculator UI

### PR DESCRIPTION
**Pull request by MahendraDani**
## Related Issue

Closes: #32 

## Description of Changes

- Created the Carbon footprint calculator page for the website as per the provided design.
- The page is fully responsive for desktop, tablet and mobile viewports.
- The route for the page is `http://localhost:3000/dashboard`
- I have not added any button which routes to that page, so please **type the route manually**. 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots/Videos
Please provide any necessary screenshots/videos to illustrate the changes made.

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/a607ce85-36cf-410c-9eff-c511e832f50c

### CODE REVIEW

**Comment by MahendraDani** [comment]
@shreya024 I have not added any button that route to this page as it was not mentioned.
- I think the `Greetings` workflow has some errors.
- `Vercel test` is failed due to authorization from repo owner, there's no bugs from my side.
Here's the screenshot obtained after checking details of the test.
Capture

** Hence I have made a clean PR and there are no bugs from my side**

Please let me know if there are any changes!
Thanks

**Review by shreya024 — CHANGES_REQUESTED** [review]
@MahendraDani Could you change the naming and routing to /calculate because we have a different dashboard planned.

**Comment by MahendraDani** [comment]
@shreya024 The `dashboard` written on the top right corner needs to be changed to `Calculate` also?

**Comment by shreya024** [comment]
No no just the routes and component name

**Comment by MahendraDani** [comment]
@shreya024 
- Changed the api endpoint as `http://localhost:3000/calculate`
- Changed the component name to `Calucalte`

## Screenshots
fix_carbonops_calculate

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
