### PR TITLE
UI improvement About us done

### PR DESCRIPTION
**Pull request by Hemant2335**
## Related Issue
The issue was to create a about us page based on the given design

Closes: #30

## Description of Changes
the changes are
-> Created a new page About
-> Added link on navbar mobile and desk view

## Checklist:

- [x ] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.

## Screenshots

Updated
Screenshot (135)
Screenshot (134)
Screenshot (132)
Screenshot (131)
Screenshot (138)
Screenshot (137)
Screenshot (136)

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello Hemant2335, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by SrijanShovit** [comment]
I think the green color used for Who We Are box is too light.
Please make it somewhat darker(mixing with the theme color of websute) and make the text color white.

**Comment by Hemant2335** [comment]
The mentioned changes have been done please check 

ss
Screenshot (142)

**Comment by SrijanShovit** [comment]
Personally, I would like a little more dark like the exact green of logo.
What do @shreya024 you say?

**Comment by shreya024** [comment]
> Personally, I would like a little more dark like the exact green of logo. What do @shreya024 you say?

Yeah I would agree. @Hemant2335 Also resolve the merge conflicts and push again

**Comment by Hemant2335** [comment]
Yaa I have changed the color same as that of the logo

here the ss

Screenshot (148)

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
