### PR TITLE
Improvement: Optimize image paths for better maintainability

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

Closes: #152 [issue number]

## Description of Changes

- Changed image path relative to the public folder.

It will fix the Logo Image path in home page.
It will fix the issue of invalid path if the folder structure is modified.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| image | image |

Logo image is fixed

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello s2sharpit, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by s2sharpit** [comment]
Hey @shreya024, Please review this pr.

**Comment by s2sharpit** [comment]
Hey @SrijanShovit @shreya024 
I would request you to review this pr ASAP.

**Review by shreya024 — APPROVED** [review]

**Comment by s2sharpit** [comment]
Hi @SrijanShovit and @shreya024,
The pull request has been approved. Could you please take a look and merge it if everything looks good? Thank you!

**Pull request merged**
