### PR TITLE
added individual dashboard ui

### PR DESCRIPTION
**Pull request by Ida-Naliaka**
## Related Issue

Closes: #104 

## Description of Changes

- installed emotion/react, emotion/styled and emotion/core packages
- added ibmplex semibold font in the public/fonts 
- added the pus icon in public/icons
- added the placeholder profile image, the footprint image and the visitors info image in public/images/individual
- Adjusted the login component to have the login button navigate to /myprofile
- Created the individual dashboard ui which has a profile card displaying user information,
- the pencil icon opens and closes the edit side drawer
- the plus icon on the navbar opens and closes the actions component which has the create, feeds and events buttons.
- the feeds button navigates to /feeds, the events button navigates to /navigate
- the stats component contains the calculate button routed to /calculate
- the chart component contains the visitor information chart -image

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

nobuttonsclicked
sidedrawer
fullsidedrawer
actionscomponentopen

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello Ida-Naliaka, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Review by shreya024 — APPROVED** [review]

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Ida-Naliaka Resolve the merge conflicts and push again

**Comment by Ida-Naliaka** [comment]
Conflicts resolved

**Comment by shreya024** [comment]
> `package-lock.json`
> `package.json`
> `yarn.lock`

@Ida-Naliaka Resolve the conflicts in package-lock.json,package.json and yarn.lock and I'll merge

**Comment by Ida-Naliaka** [comment]
Hi @shreya, all conflicts resolved.

**Review by shreya024 — APPROVED** [review]

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Ida-Naliaka Resolve the conflicts

**Comment by Ida-Naliaka** [comment]
@shreya024 conflicts resolved, please merge

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
