### PR TITLE
feat : Created fully responsive homepage

### LINKED ISSUE #18: Home Page UI Implementation
## Description:
- Implement HomePage UI using NextUI/muI and Tailwind CSS according to the following design
- Make sure that the UI is fully responsive

## Design:
 
HOME PAGE

### PR DESCRIPTION
**Pull request by MahendraDani**
Fixes #18 

## Description
A full responsive homepage is developed for the website according to the give design.

## Features included
1. Responsive `Navbar` with **hamburger menu** and **scroll effect**.
2. Responsive `hero section`.
3. Responsive `services section`.
4. Responsive `Carbon Graph section`.
5. Responsive `organizations section`.
6. Responsive `footer` with **about us** and **contact us** section.

## Outcomes

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/172a656b-3887-4df3-9321-0e757e7b0b2a

### CODE REVIEW

**Comment by MahendraDani** [comment]
@shreya024 If there are any changes please let me know!
Thanks!

**Comment by MahendraDani** [comment]
@shreya024 Would you please merge these pull request if there aren't any changes?

**Comment by shreya024** [comment]
> @shreya024 Would you please merge this pull request if there aren't any changes?

Hey @MahendraDani Great job  👍 .We will be integrating vercel soon in the project.And merge it after seeing it once on the deployment workflow.

**Comment by MahendraDani** [comment]
@shreya024 Alright!
Thanks!

**Review by shreya024 — APPROVED** [review]
LGTM !

**Pull request merged**
