### PR TITLE
feat: add login and logout using google auth

### PR DESCRIPTION
**Pull request by suzy-g38**
## Related Issue

Closes: #42

## Description of Changes

Add login with google option and after someone logged in with google they will redirect to the home page and there will be a logout button in the place of login button to logout from the session.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

login page

image

logout option

image

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello suzy-g38, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by suzy-g38** [comment]
@shreya024 let me know if you think there is anything that needs to be changed.

**Review by shreya024 — CHANGES_REQUESTED** [review]
Remove the keys,put .env in gitignore and add an env example file having same structure as .env

**Review by suzy-g38 — COMMENTED** [review]
updated the changes that were asked for. Didn't add .env in gitignore as that is already mentioned there as .env.local.

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
