### PR TITLE
#57 Greeting bot added

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

Closes: #57 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by shreya024** [comment]
> @shreya024 you have to merge it 
> i have completed from my side

Hey @k-deepak04 please be patient.It is under review.

**Comment by shreya024** [comment]
> @shreya024 you have to merge it 
> i have completed from my side

Hey @k-deepak04 please be patient.It is under review.

**Review by shreya024 — APPROVED** [review]

**Comment by k-deepak04** [comment]
To resolve this issue, you need to make sure you have a valid GitHub token with the appropriate permissions. Here are the steps you can follow:

Go to the GitHub repository where you want to run the action.
Click on the "Settings" tab.
In the left sidebar, click on "Secrets."
Create a new secret by clicking on "New repository secret."
Provide a name for the secret, such as "GITHUB_TOKEN" or any other name you prefer.
Generate a new token from GitHub with the necessary permissions. Make sure the token has access to the repository, including the ability to create issues and pull requests.
Copy the generated token.
Go back to the secrets page on GitHub and paste the token into the "Value" field for the newly created secret.
Save the secret.

@shreya024 you have to do this at your side then this bot will work

**Comment by k-deepak04** [comment]
image

i checked this one token is empty there that's why depandabot pr is also failing
please do the needful :)

**Comment by shreya024** [comment]
> image
> 
> i checked this one token is empty there that's why depandabot pr is also failing please do the needful :)

We have added token now,but still facing the same issue

**Comment by k-deepak04** [comment]
Give me time i will look deeply into the subject matter
as i'm having ESE from 6th i will look into this after 14th june

**Pull request merged**
