### PR TITLE
Added Scroll to Top

### PR DESCRIPTION
**Pull request by Deepanshu0703**
I added the scroller option . This is a dynamic scroller and will only be visible if  you are not already in Top.

### CODE REVIEW

**Comment by Deepanshu0703** [comment]
This PR is under issue #13 assigned to me

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Deepanshu0703 While scrolling down,the Header space is increased.Please fix it.
image

**Comment by Deepanshu0703** [comment]
I haven't change anything in the existing code i just added few parts. And this navbar thing is showing this only , while I cloned and started it locally. Still I will see it and make the required changes .

**Review by shreya024 — APPROVED** [review]

**Comment by shreya024** [comment]
> I haven't change anything in the existing code i just added few parts. And this navbar thing is showing this only , while I cloned and started it locally. Still I will see it and make the required changes .

Hey @Deepanshu0703 merging this as the bug is only visible in vercel deployment and not in local.Good job !

**Pull request merged**
