### PR TITLE
added the animation on hero sec

### PR DESCRIPTION
**Pull request by parasss19**
## Related Issue

Closes: #67

## Description of Changes
Added the animation on hero section (text and image both)

## Checklist:

- [ yes] My code adheres to the established style guidelines of this project.
- [ ues] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [yes ] My changes have not introduced any new warnings.

## Updated

https://github.com/SrijanShovit/carbonops-v2/assets/101205226/bfb0722f-f133-46ff-a0ed-0a098168f72e

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello parasss19, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by SrijanShovit** [comment]
There is no point in adding animation to A place to calculate..................
Animations should not be added to anything
Also the animation added to right side photo will be good when the page loads.
You can have added floating animation of size increasing and decreasing after being loaded.

**Comment by parasss19** [comment]
> There is no point in adding animation to A place to calculate.................. Animations should not be added to anything Also the animation added to right side photo will be good when the page loads. You can have added floating animation of size increasing and decreasing after being loaded.

So exactly where should I apply the animation? Photo Or text?

**Comment by parasss19** [comment]
Hii @shreya024 please review the PR or if you want any changes then let me know

**Comment by shreya024** [comment]
> There is no point in adding animation to A place to calculate.................. Animations should not be added to anything Also the animation added to right side photo will be good when the page loads. You can have added floating animation of size increasing and decreasing after being loaded.

@parasss19 Make these changes

**Comment by parasss19** [comment]
> > There is no point in adding animation to A place to calculate.................. Animations should not be added to anything Also the animation added to right side photo will be good when the page loads. You can have added floating animation of size increasing and decreasing after being loaded.
> 
> @parasss19 Make these changes

Hi @shreya024 I have added the floating animation on text so please review it once

**Review by shreya024 — APPROVED** [review]

**Pull request merged**
