### PR TITLE
Applied the dark theme

### PR DESCRIPTION
**Pull request by parasss19**
Closes: #62

## Description of Changes
- Applied the dark mode button with toggle effects
- used google icons for sun moon img
- also made the navbar initially transparent so that on scroll it will change color

## Checklist:

- [ x] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [x ] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.

### CODE REVIEW

**Review by SrijanShovit — COMMENTED** [review]
Hello parasss19, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

**Comment by parasss19** [comment]
Hey @shreya024 @SrijanShovit Please review it 
I closed previous PR because of conflicts now .

**Review by shreya024 — CHANGES_REQUESTED** [review]
@parasss19 Take a pull and resolve the merge conflicts

**Comment by parasss19** [comment]
> @parasss19 Take a pull and resolve the merge conflicts

Hey @shreya024 please review it now

**Review by shreya024 — APPROVED** [review]

**Comment by shreya024** [comment]
@parasss19 Resolve the merge conflict

**Comment by parasss19** [comment]
> @parasss19 Resolve the merge conflict and I'll merge

hey @shreya024 Please merge it now

**Pull request merged**
