### PR TITLE
Contact Us UI

### LINKED ISSUE #33: Contact US UI Implementation
## Description:
- Implement Contact Us UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the Contact Us button on HomePage,this page will open
- Make sure that the UI is fully responsive

## Design:
Contact us and feedback page

### PR DESCRIPTION
**Pull request by Soulpurr**
So i have added a contact us page.
screenshot-
scrnli_26_06_2023_19-15-26
pls do add gssoc23 and level label in the pr.
fixes #33

### CODE REVIEW

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Soulpurr Make the UI as per given design in #33

**Comment by Soulpurr** [comment]
> @Soulpurr Make the UI as per given design in #33

That one that one not even look responsive.The design j have given is better than that.

**Comment by SrijanShovit** [comment]
@Soulpurr Your design shall be good; no doubts about that. However, it should match with all the pages in project. Hope you understand and make changes accordingly.

For contacting us, we don't need any agreement on TnCs.That can be included in signup page.

**Comment by Soulpurr** [comment]
> @Soulpurr Your design shall be good; no doubts about that. However, it should match with all the pages in project. Hope you understand and make changes accordingly.
> 
> For contacting us, we don't need any agreement on TnCs.That can be included in signup page.

Okk can you just share the design image again on issue section.

**Comment by shreya024** [comment]
> > @Soulpurr Your design shall be good; no doubts about that. However, it should match with all the pages in project. Hope you understand and make changes accordingly.
> > For contacting us, we don't need any agreement on TnCs.That can be included in signup page.
> 
> Okk can you just share the design image again on issue section.

It is shared already [here](https://github.com/SrijanShovit/carbonops-v2/issues/33)

**Comment by Soulpurr** [comment]
> > > @Soulpurr Your design shall be good; no doubts about that. However, it should match with all the pages in project. Hope you understand and make changes accordingly.
> > > For contacting us, we don't need any agreement on TnCs.That can be included in signup page.
> > 
> > 
> > Okk can you just share the design image again on issue section.
> 
> It is shared already [here](https://github.com/SrijanShovit/carbonops-v2/issues/33)

Just give me some time as my end sem are going on.

**Comment by Soulpurr** [comment]
@shreya024  i have made changes do verify and acknowledge this.
scrnli_07_07_2023_20-12-40

**Review by shreya024 — CHANGES_REQUESTED** [review]
@Soulpurr Take a pull and resolve the merge conflicts

**Comment by Soulpurr** [comment]
> @Soulpurr Take a pull and resolve the merge conflicts

You mean running git pull right?

**Comment by shreya024** [comment]
> > @Soulpurr Take a pull and resolve the merge conflicts
> 
> You mean running git pull right?

Yes and then resolve the conflicts and push again

**Pull request closed without merging**
